export const UserModel = {
  id: true,
  name: true,
  user_name: true,
  email: true,
  email_verified: true,
  // password: true,
  // otp: true,
  // otp_created_at: true,
  // threads: true,
  // comments: true,
  // liked_threads_ids: true,
  // liked_threads: true,
  // disliked_threads_ids: true,
  // disliked_threads: true,
  // liked_comments_ids: true,
  // liked_comments: true,
  // disliked_comments_ids: true,
  // disliked_comments: true,
  // createdAt: true,
  // updatedAt: true
};

export const ThreadModel = {
  id: true,
  user_id: true,
  heading: true,
  content: true,
  likes: true,
  dislikes: true,
  // user: true,
  // liked_by_ids: true,
  // liked_by: true,
  // disliked_by_ids: true,
  // disliked_by: true,
  // comments: true,
  // createdAt: true,
  // updatedAt: true,
};

export const CommentModel = {
  id: true,
  user_id: true,
  content: true,
  likes: true,
  dislikes: true,
  // user: true,
  // thread: true,
  // thread_id: true,
  // liked_by_ids: true,
  // liked_by: true,
  // disliked_by_ids: true,
  // disliked_by: true,
  // comment_id: true,
  // comment: true,
  // comments: true,
  // createdAt: true,
  // updatedAt: true
};
